# https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://s3.amazonaws.com/anyfront.dev/try.cloudformation.yml&stackName=anyfront-1click-deploy
#    &param_GitUrl=...
#    &param_DomainName=...

AWSTemplateFormatVersion: 2010-09-09

Description: 'This stack creates a CodeBuild project that deploys a front end project to AWS using anyfront.dev. After deploying this stack, search for "anyfront" in the CodeBuild console and hit the "Start build" button: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects?region=us-east-1&projects-meta=eyJmIjp7InRleHQiOiJhbnlmcm9udCIsInNoYXJlZCI6ZmFsc2V9LCJzIjp7InByb3BlcnR5IjoiTEFTVF9NT0RJRklFRF9USU1FIiwiZGlyZWN0aW9uIjotMX0sIm4iOjIwLCJpIjowfQ'
Parameters:
  GitUrl:
    Type: String
    Description: URL of the git repository containing your front end project to deploy, make sure to include the protocol (https:// for example)
  DomainName:
    Type: String
    Description: Domain name to use for the application, make sure you have a hosted zone in Route53 for this domain


Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'anyfront-deploy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - '*'
                Resource:
                  - '*'
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Deploys a front end project to AWS using anyfront.dev
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: GIT_URL
            Value:
              Ref: GitUrl
          - Name: DOMAIN
            Value:
              Ref: DomainName
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Name:
        Fn::Join:
          - "-"
          - - "anyfront-deployment"
            - !Join [ "-", !Split [ ".", !Ref DomainName ] ]
      ServiceRole:
        Ref: CodeBuildServiceRole
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - curl -fsSL https://hub.barbe.app/install.sh -o install-barbe.sh
                - sh install-barbe.sh
                - mkdir tmp && cd tmp
                - barbe apply anyfront/git-aws.hcl --env GIT_URL --env DOMAIN --log-level debug
