<script>
    import HeadingLink from "@/components/HeadingLink.svelte";
    import CodeBlock from "@/components/CodeBlock.svelte";
    import Toc from "@/components/Toc.svelte";
</script>

<p>
    The most common task when using PocketBase as framework probably would be querying and working with your
    collection records.
</p>

<Toc />

<HeadingLink title="Get/Set record fields" />
<p>
    All available <code>models.Record</code> getter and setters are listed in the
    <a href="{import.meta.env.PB_GODOC_URL}/models#Record" target="_blank" rel="noopener noreferrer">
        godoc of the model
    </a>, but below you could find some examples:
</p>
<CodeBlock
    language="go"
    content={`
        // change the specified record field value to 123
        record.Set("someField", 123)

        // export the public safe record fields as map[string]any
        record.PublicExport()

        // returns a new model copy populated with the original/intial record data
        // (could be useful if you want to compare old and new field values)
        record.OriginalCopy()

        // retrieve a single record field value
        record.Get("someField")            // -> as any
        record.GetBool("someField")        // -> as bool
        record.GetString("someField")      // -> as string
        record.GetInt("someField")         // -> as int
        record.GetFloat("someField")       // -> as float64
        record.GetTime("someField")        // -> as time.Time
        record.GetDateTime("someField")    // -> as types.DateTime
        record.GetStringSlice("someField") // -> as []string

        // auth records only
        // ---
        record.Username()
        record.SetUsername("john.doe")
        // ---
        record.Email()
        record.SetEmail("test@example.com")
        // ---
        record.EmailVisibility()
        record.SetEmailVisibility(false)
        // ---
        record.Verified()
        record.SetVerified(false)
        // ---
        record.TokenKey()
        record.SetTokenKey("ABCD123")
        record.RefreshTokenKey() // sets autogenerated TokenKey
        // ---
        record.LastResetSentAt()
        record.SetLastResetSentAt(types.DateTime{})
        // ---
        record.LastVerificationSentAt()
        record.SetLastVerificationSentAt(types.DateTime{})
        // ---
        record.PasswordHash()
        record.SetPassword("123456")
        record.ValidatePassword("123456")
    `}
/>

<HeadingLink title="Fetch records" />

<HeadingLink title="Fetch single record" tag="h5" />
<CodeBlock
    language="go"
    content={`
        // retrieve a single "articles" collection record by its id
        record, err := app.Dao().FindRecordById("articles", "RECORD_ID")

        // retrieve a single "articles" collection record by a single key-value pair
        record, err := app.Dao().FindRecordByData("articles", "slug", "test")
    `}
/>

<HeadingLink title="Fetch multiple records" tag="h5" />
<CodeBlock
    language="go"
    content={`
        // retrieve multiple "articles" collection records by their ids
        records, err := app.Dao().FindRecordsByIds("articles", []string{"RECORD_ID1", "RECORD_ID2"})

        // retrieve multiple "articles" collection records by a custom dbx expression(s)
        records, err := app.Dao().FindRecordsByExpr("articles",
            dbx.HashExp{"status": "pending"},
            // or even raw expressions
            dbx.NewExp("LOWER(username) = {:username}", dbx.Params{"username": "John.Doe"}),
        )
    `}
/>

<HeadingLink title="Fetch auth records" tag="h5" />
<CodeBlock
    language="go"
    content={`
        // retrieve a single auth collection record by its email
        user, err := app.Dao().FindAuthRecordByEmail("users", "test@example.com")

        // retrieve a single auth collection record by its username (case insensitive)
        user, err := app.Dao().FindAuthRecordByUsername("users", "John.Doe")

        // retrieve a single auth collection record by its JWT token (auth, password reset, etc.)
        user, err := app.Dao().FindAuthRecordByToken("JWT_TOKEN", app.Settings().RecordAuthToken.Secret)
    `}
/>

<HeadingLink title="Create new record" />

<HeadingLink title="Create new record WITHOUT data validations" tag="h5" />
<CodeBlock
    language="go"
    content={`
        import (
            "github.com/pocketbase/pocketbase/models"
        )

        ...

        collection, err := app.Dao().FindCollectionByNameOrId("articles")
        if err != nil {
            return err
        }

        record := models.NewRecord(collection)
        record.Set("title", "Lorem ipsum")
        record.Set("active", true)
        record.Set("someOtherField", 123)

        if err := app.Dao().SaveRecord(record); err != nil {
            return err
        }
    `}
/>

<HeadingLink title="Create new record WITH data validations" tag="h5" />
<CodeBlock
    language="go"
    content={`
        import (
            "github.com/pocketbase/pocketbase/forms"
            "github.com/pocketbase/pocketbase/models"
        )

        ...

        collection, err := app.Dao().FindCollectionByNameOrId("articles")
        if err != nil {
            return err
        }

        record := models.NewRecord(collection)

        form := forms.NewRecordUpsert(app, record)

        // or form.LoadRequest(r, "")
        form.LoadData(map[string]any{
            "title": "Lorem ipsum",
            "active": true,
            "someOtherField": 123,
        })

        // validate and submit (internally it calls app.Dao().SaveRecord(record) in a transaction)
        if err := form.Submit(); err != nil {
            return err
        }
    `}
/>

<HeadingLink title="Intercept record before create API hook" tag="h5" />
<CodeBlock
    language="go"
    content={`
        import (
            "github.com/pocketbase/pocketbase/apis"
            "github.com/pocketbase/pocketbase/core"
        )

        ...

        app.OnRecordBeforeCreateRequest().Add(func(e *core.RecordCreateEvent) error {
            if (e.Record.Collection().Name == "articles") {
                // overwrite the submitted "active" field value to false
                e.Record.Set("active", false)

                // or you can also prevent the create event by returning an error, eg.:
                if (e.Record.GetString("status") != "pending") {
                    return apis.NewBadRequestError("status must be pending.", nil)
                }
            }

            return nil
        })
    `}
/>

<HeadingLink title="Update existing record" />

<HeadingLink title="Update record WITHOUT data validations" tag="h5" />
<CodeBlock
    language="go"
    content={`
        record, err := app.Dao().FindRecordById("articles", "RECORD_ID")
        if err != nil {
            return err
        }

        record.Set("title", "Lorem ipsum")
        record.Set("active", true)
        record.Set("someOtherField", 123)

        if err := app.Dao().SaveRecord(record); err != nil {
            return err
        }
    `}
/>

<HeadingLink title="Update record WITH data validations" tag="h5" />
<CodeBlock
    language="go"
    content={`
        import (
            "github.com/pocketbase/pocketbase/forms"
        )

        ...

        record, err := app.Dao().FindRecordById("articles", "RECORD_ID")
        if err != nil {
            return err
        }

        form := forms.NewRecordUpsert(app, record)

        // or form.LoadRequest(r, "")
        form.LoadData(map[string]any{
            "title": "Lorem ipsum",
            "active": true,
            "someOtherField": 123,
        })

        // validate and submit (internally it calls app.Dao().SaveRecord(record) in a transaction)
        if err := form.Submit(); err != nil {
            return err
        }
    `}
/>

<HeadingLink title="Intercept record before update API hook" tag="h5" />
<CodeBlock
    language="go"
    content={`
        import (
            "github.com/pocketbase/pocketbase/apis"
            "github.com/pocketbase/pocketbase/core"
        )

        ...

        app.OnRecordBeforeUpdateRequest().Add(func(e *core.RecordUpdateEvent) error {
            if (e.Record.Collection().Name == "articles") {
                // overwrite the submitted "active" field value to false
                e.Record.Set("active", false)

                // or you can also prevent the create event by returning an error, eg.:
                if (e.Record.GetString("status") != "pending") {
                    return apis.NewBadRequestError("status must be pending.", nil)
                }
            }

            return nil
        })
    `}
/>

<HeadingLink title="Delete record" />
<CodeBlock
    language="go"
    content={`
        record, err := app.Dao().FindRecordById("articles", "RECORD_ID")
        if err != nil {
            return err
        }

        if err := app.Dao().DeleteRecord(record); err != nil {
            return err
        }
    `}
/>

<HeadingLink title="Custom record query" />
<CodeBlock
    language="go"
    content={`
        import (
            "github.com/pocketbase/dbx"
            "github.com/pocketbase/pocketbase/daos"
            "github.com/pocketbase/pocketbase/models"
        )

        ...

        func FindActiveArticles(dao *daos.Dao) ([]*models.Record, error) {
            collection, err := dao.FindCollectionByNameOrId("articles")
            if err != nil {
                return nil, err
            }

            query := dao.RecordQuery(collection).
                AndWhere(dbx.HashMap{"status": "active"}).
                OrderBy("published DESC").
                Limit(10)

            rows := []dbx.NullStringMap{}
            if err := query.All(&rows); err != nil {
                return nil, err
            }

            return models.NewRecordsFromNullStringMaps(collection, rows), nil
        }
    `}
/>
